# Prefer Docker for monorepo reliability on Railway.
# Start command comes from Dockerfile CMD (includes prisma db push).
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 90
restartPolicyType = "ON_FAILURE"
